version: '3.8'

services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: rest_app
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 567234
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  web:
    build: .
    depends_on:
      - postgres
      - redis
    environment:
      DB_URL: postgresql+asyncpg://postgres:567234@postgres:5432/rest_app
    ports:
      - "8000:8000"
    volumes:
      - .:/app
